name: Update Solr on PDF Change

on:
  push:
    paths:
      - 'Documenti/**'

jobs:
  update-solr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Resolve package conflicts
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          apt-utils \
          ca-certificates \
          gnupg \
          lsb-release

    - name: Set up Docker
      run: |
        sudo apt-get install -y \
          docker-ce \
          docker-ce-cli \
          containerd.io

    - name: Build and run Solr Docker container
      run: |
        docker build -t my-solr ./docker
        docker run -d -p 8983:8983 --name my-solr-container my-solr

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests PyMuPDF

    - name: Check Solr Status
      run: |
        curl -s http://localhost:8983/solr/admin/cores?action=STATUS
        docker logs my-solr-container

    - name: Run Solr Update Script
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs
      run: python ScriptRAS2.py
