name: Update Solr on PDF Change

on:
  push:
    paths:
      - 'Documenti/**'

jobs:
  update-solr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: sudo apt-get install docker.io

    - name: Build and run Solr docker container
      run: |
        docker build -t my-solr ./docker
        docker run -d -p 8983:8983 --name my-solr-container my-solr

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests PyMuPDF

    - name: Run Solr Update Script
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs
      run: python ScriptRAS2.py
