name: Update Solr on PDF Change

on:
  push:
    paths:
      - 'Documenti/**'

jobs:
  update-solr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Resolve Package Conflicts
      run: |
        sudo apt-get update
        sudo apt-get remove -y containerd containerd.io || true
        sudo apt-get purge -y containerd containerd.io || true
        sudo apt-get autoremove -y

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build and Run Solr Docker Container
      run: |
        docker build -t my-solr ./docker
        docker run -d -p 8983:8983 --name my-solr-container my-solr
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs

    - name: Check Solr Container Logs
      run: |
        echo "Checking Solr container logs..."
        docker logs my-solr-container
        echo "Solr container logs checked."

    - name: Wait for Solr to be Ready
      run: |
        # Wait until Solr responds to HTTP requests
        for i in {1..30}; do
          if curl --output /dev/null --silent --head --fail "$SOLR_URL"; then
            echo "Solr is ready."
            exit 0
          else
            echo "Waiting for Solr..."
            sleep 15
          fi
        done
        echo "Solr did not become ready in time." >&2
        exit 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests PyMuPDF

    - name: Run Solr Update Script
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs
        GITHUB_REPO: Refio22/Rag-Unisannio
        DIRECTORY_PATH: Documenti
      run: python ScriptRAS2.py
