name: Update Solr on PDF Change

on:
  push:
    paths:
      - 'Documenti/**'

jobs:
  update-solr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Java
      run: sudo apt-get install -y openjdk-11-jdk

    - name: Wait for Solr to be Ready
      run: |
        for i in {1..30}; do
          if curl --output /dev/null --silent --head --fail "http://localhost:8983/solr/regolamento_1"; then
            echo "Solr is ready."
            exit 0
          else
            echo "Waiting for Solr..."
            sleep 15
          fi
        done
        echo "Solr did not become ready in time." >&2
        exit 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests PyMuPDF

    - name: Run Solr Update Script
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs
        GITHUB_REPO: Refio22/Rag-Unisannio
        DIRECTORY_PATH: Documenti
      run: python ScriptRAS2.py
