name: Update Solr on PDF Change

on:
  push:
    paths:
      - 'Documenti/**'

jobs:
  update-solr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Resolve Package Conflicts
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          apt-utils \
          ca-certificates \
          gnupg \
          lsb-release \
          curl

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests PyMuPDF

    - name: Run Solr Update Script
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs
        GITHUB_REPO: Refio22/Rag-Unisannio
        DIRECTORY_PATH: Documenti
      run: python ScriptRAS2.py
