name: Update Solr on PDF Change

on:
  push:
    paths:
      - 'Documenti/**'

jobs:
  update-solr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Docker using Official Script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: Start Docker Service
      run: sudo systemctl start docker

    - name: Build and Run Solr Docker Container
      run: |
        docker build -t my-solr ./docker
        docker run -d -p 8983:8983 --name my-solr-container my-solr
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs

    - name: Wait for Solr to be Ready
      run: |
        # Wait until Solr responds to HTTP requests
        until $(curl --output /dev/null --silent --head --fail "$SOLR_URL"); do
          echo "Waiting for Solr..."
          sleep 5
        done
        echo "Solr is ready."

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests PyMuPDF

    - name: Run Solr Update Script
      env:
        SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs
        GITHUB_REPO: Refio22/Rag-Unisannio
        DIRECTORY_PATH: Documenti
      run: python ScriptRAS2.py
